---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    strategy:
      matrix:
        target:
          - gui
          - nogui
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/isomorphic-copy
          tags: ${{ matrix.target }}
          Dockerfile: docker/${{ matrix.target }}/Dockerfile

